services:
  - type: web
    name: kovalenko-candles
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "node server/index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
    autoDeploy: true
    previewsEnabled: true
    previewPlan: free